### PR TITLE
Develop/audrey

### PR DESCRIPTION
**Pull request by audreylbx**

### CODE REVIEW

**Review by pefavre — CHANGES_REQUESTED** [review]
I'm unsure about the button leading to the website next to the logo. Could we move further? Or rely on the link in the menu?
The subscribe button at the bottom is for RSS subscription?

**Comment by simontoussaint** [comment]
removed RSS button

**Comment by pefavre** [comment]
@simontoussaint I'm not sure you did

**Comment by simontoussaint** [comment]
image
@pefavre anything that shouldn't be there?

**Comment by pefavre** [comment]
The Subscribe button is still there:

screen_shot_2017-06-30_at_17_25_09

**Comment by simontoussaint** [comment]
Don't know who did that. I suspect a marketer with low integration knowledge.

**Comment by simontoussaint** [comment]
@pefavre should be fixed now. Sorry for the double trouble!

**Comment by pefavre** [comment]
Your changes must still be in local, because it's still not there :)
We'll investigate tomorrow

**Pull request merged**
